### ISSUE TITLE
Error on startup Paper 1.16.5

### ISSUE THREAD

**Issue by Kenaestic** [AlonsoAliaga/BetterHeads#1]
**Describe the bug**
Startup error.

```
[02:54:53 ERROR]: Error occurred while enabling BetterHeads v1.2-BETA (Is it up to date?)
java.lang.IllegalArgumentException: UUID string too large
	at java.util.UUID.fromString(Unknown Source) ~[?:?]
	at com.alonsoaliaga.betterheads.BetterHeads.loadCurrentDatabaseHeads(BetterHeads.java:333) ~[?:?]
	at com.alonsoaliaga.betterheads.BetterHeads.startUpLoadHeads(BetterHeads.java:291) ~[?:?]
	at com.alonsoaliaga.betterheads.BetterHeads.onEnable(BetterHeads.java:151) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-715]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-715]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-715]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-715]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-715]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:593) ~[patched_1.16.5.jar:git-Paper-715]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:281) ~[patched_1.16.5.jar:git-Paper-715]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1068) ~[patched_1.16.5.jar:git-Paper-715]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Paper-715]
	at java.lang.Thread.run(Unknown Source) [?:?]
[02:54:53 INFO]: [BetterHeads] Disabling BetterHeads v1.2-BETA
```

**To Reproduce**
1. Download paper 1.16.5
2. Start server
3. Error code

**Expected behavior**
Plugin should enable.

**Screenshots**
Invalid.

**Important (please complete the following information):**
 - Java version: [11 hotspot]
 - Plugin version: [ v1.2-BETA ]
 - Server version [Paperspigot 1.16.5]

**Additional context**
None.

**Comment by AlonsoAliaga** [comment]
I can't tell if issue is related to java11 or not. Share **full** console log on startup in a bin. Error is related to an uuid that is not formatted correctly, you added any new head directly in config file? It happens on a fresh install? If so, go to BetterHeads wiki and there should be a default config with many heads, try copying it in heads.yml
Don't forget to send the entire log on a fresh install

**Comment by Kenaestic** [comment]
Yup you're exactly right. I don't know why I didn't think of regenerating the config files. Looks like something broke it somehow, I still can't pinpoint where the problem was. But there's nothing wrong with your plugin because it works now. Thanks for the quick response and sorry I wasted your time.
