### ISSUE TITLE
heads.yml is no longer accepted due to paper's latest SnakeYML update

### ISSUE THREAD

**Issue by Folas1337** [AlonsoAliaga/BetterHeads#3]
**Describe the bug**
As announced by paper 2 days ago, they've basically updated their SnakeYAML library:
![image](https://user-images.githubusercontent.com/39222968/192139167-7aba0b8f-736e-4b47-b100-f2144a995e28.png)
This affects BetterHeads in that the heads.yml is now seen as too long:
```
[10:29:22] [Server thread/INFO]: [BetterHeads] Enabling BetterHeads v1.3-BETA
[10:29:22] [Server thread/INFO]: [BetterHeads] Inventory title with support for more than 32 characters. Skipping..
[10:29:22] [Server thread/INFO]: [BetterHeads] Hex colors are available! Ready for RGB..
[10:29:22] [Server thread/INFO]: [BetterHeads] Old constructor for HoverEvent found! Using it..
[10:29:22] [Server thread/INFO]: [BetterHeads] New sendTitle method found! Using it..
[10:29:22] [Server thread/INFO]: [BetterHeads] New setUnbreakable method found! Using it..
[10:29:22] [Server thread/INFO]: [BetterHeads] New isUnbreakable method found! Using it..
[10:29:22] [Server thread/INFO]:   ___      _   _           _  _             _    
[10:29:22] [Server thread/INFO]:  | _ ) ___| |_| |_ ___ _ _| || |___ __ _ __| |___
[10:29:22] [Server thread/INFO]:  | _ \/ -_)  _|  _/ -_) '_| __ / -_) _` / _` (_-<
[10:29:22] [Server thread/INFO]:  |___/\___|\__|\__\___|_| |_||_\___\__,_\__,_/__/
[10:29:22] [Server thread/INFO]: 
[10:29:22] [Server thread/INFO]:    Running plugin BetterHeads v1.3-BETA
[10:29:22] [Server thread/INFO]:    Server running Paper version git-Paper-173 (MC: 1.19.2)
[10:29:22] [Server thread/INFO]:    (Implementing API version git-Paper-173 (MC: 1.19.2))
[10:29:22] [Server thread/INFO]:    (Developed by  AlonsoAliaga - Thanks for using my plugin ❤)
[10:29:22] [Server thread/INFO]:    Join our official discord server to receive support in alonsoaliaga.com/discord
[10:29:22] [Server thread/INFO]:    If you loved the plugin consider leaving a review and mentioning your server IP in it!
[10:29:22] [Server thread/INFO]: 
[10:29:22] [Server thread/INFO]: ===================================================================================
[10:29:22] [Server thread/INFO]: [BetterHeads] You are using a Paper fork (Paper). Plugin might have errors
[10:29:22] [Server thread/INFO]: [BetterHeads] and not work properly. Consider using SPIGOT!
[10:29:22] [Server thread/INFO]: [BetterHeads] This is not an error! This is just a warning to let you know that this
[10:29:22] [Server thread/INFO]: [BetterHeads] plugin has not been tested on paper forks. This plugin was made for spigot
[10:29:22] [Server thread/INFO]: [BetterHeads] and has been tested on spigot only. If you have issues report them to the
[10:29:22] [Server thread/INFO]: [BetterHeads] developer instead of reviewing 1 star. Thanks in advanced!
[10:29:22] [Server thread/INFO]: [BetterHeads] Join our official support server on alonsoaliaga.com/discord
[10:29:22] [Server thread/INFO]: ===================================================================================
[10:29:22] [Server thread/INFO]: 
[10:29:22] [Server thread/INFO]: [BetterHeads] BungeeCord action bar available. Hooking..
[10:29:22] [Server thread/INFO]: [BetterHeads] ProtocolLib found! Checking..
[10:29:22] [Server thread/ERROR]: Cannot load plugins/BetterHeads/heads.yml
org.bukkit.configuration.InvalidConfigurationException: org.yaml.snakeyaml.error.YAMLException: The incoming YAML document exceeds the limit: 3145728 code points.
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:105) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:305) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at com.alonsoaliaga.betterheads.others.FileManager$Configuration.init(FileManager.java:58) ~[BetterHeads.jar:?]
	at com.alonsoaliaga.betterheads.others.FileManager$Configuration.<init>(FileManager.java:51) ~[BetterHeads.jar:?]
	at com.alonsoaliaga.betterheads.others.FileManager.setupConfigFile(FileManager.java:32) ~[BetterHeads.jar:?]
	at com.alonsoaliaga.betterheads.others.FileManager.<init>(FileManager.java:20) ~[BetterHeads.jar:?]
	at com.alonsoaliaga.betterheads.BetterHeads.onEnable(BetterHeads.java:107) ~[BetterHeads.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-173]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-173]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.19.2.jar:git-Paper-173]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.2.jar:git-Paper-173]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.2.jar:git-Paper-173]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[paper-1.19.2.jar:git-Paper-173]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-173]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: org.yaml.snakeyaml.error.YAMLException: The incoming YAML document exceeds the limit: 3145728 code points.
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:335) ~[snakeyaml-1.32.jar:?]
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:256) ~[snakeyaml-1.32.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:648) ~[snakeyaml-1.32.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:171) ~[snakeyaml-1.32.jar:?]
	at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:57) ~[snakeyaml-1.32.jar:?]
	at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:43) ~[snakeyaml-1.32.jar:?]
	at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:136) ~[snakeyaml-1.32.jar:?]
	at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:116) ~[snakeyaml-1.32.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeScalarNode(Composer.java:221) ~[snakeyaml-1.32.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:190) ~[snakeyaml-1.32.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:321) ~[snakeyaml-1.32.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:312) ~[snakeyaml-1.32.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:293) ~[snakeyaml-1.32.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:194) ~[snakeyaml-1.32.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:321) ~[snakeyaml-1.32.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:312) ~[snakeyaml-1.32.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:293) ~[snakeyaml-1.32.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:194) ~[snakeyaml-1.32.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:321) ~[snakeyaml-1.32.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:312) ~[snakeyaml-1.32.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:293) ~[snakeyaml-1.32.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:194) ~[snakeyaml-1.32.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:321) ~[snakeyaml-1.32.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:312) ~[snakeyaml-1.32.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:293) ~[snakeyaml-1.32.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:194) ~[snakeyaml-1.32.jar:?]
	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:116) ~[snakeyaml-1.32.jar:?]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:142) ~[snakeyaml-1.32.jar:?]
	at org.yaml.snakeyaml.Yaml.compose(Yaml.java:561) ~[snakeyaml-1.32.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:103) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	... 19 more
[10:29:22] [Server thread/INFO]: [Auto-update] Configuration is up-to-date!
[10:29:22] [Server thread/INFO]: [BetterHeads] Current cost type is 'MATERIAL'. Enabling..
[10:29:22] [Server thread/INFO]: [BetterHeads] Head cost is disabled in config. Skipping..
[10:29:22] [Server thread/INFO]: [BetterHeads] Version is older than 1.16 => false
[10:29:22] [Server thread/INFO]: [BetterHeads] Current heads saved in the plugin: 0
[10:29:22] [Server thread/INFO]: [BetterHeads] Current custom heads saved in the plugin: 0
[10:29:22] [Server thread/INFO]: [BetterHeads] This is plugin's first start. Plugin will start now checking for new heads! This might take many seconds!
[10:29:22] [Server thread/INFO]: [BetterHeads] Optionally, if you don't want this because of the time it might takes on start up in a future. Disable option in config.yml
[10:29:22] [Server thread/INFO]: [BetterHeads] Checking category 'alphabet'..
[10:29:27] [Server thread/INFO]: [BetterHeads] New heads found in category 'alphabet'. Loading new heads..
[10:29:27] [Server thread/INFO]: [BetterHeads] Added 5755 new heads..
[10:29:27] [Server thread/INFO]: [BetterHeads] Checking category 'animals'..
[10:29:30] [Server thread/INFO]: [BetterHeads] New heads found in category 'animals'. Loading new heads..
[10:29:30] [Server thread/INFO]: [BetterHeads] Added 3791 new heads..
[10:29:30] [Server thread/INFO]: [BetterHeads] Checking category 'blocks'..
[10:29:31] [Server thread/INFO]: [BetterHeads] New heads found in category 'blocks'. Loading new heads..
[10:29:31] [Server thread/INFO]: [BetterHeads] Added 1702 new heads..
[10:29:31] [Server thread/INFO]: [BetterHeads] Checking category 'decoration'..
[10:29:46] [Server thread/INFO]: [BetterHeads] New heads found in category 'decoration'. Loading new heads..
[10:29:46] [Server thread/INFO]: [BetterHeads] Added 10836 new heads..
[10:29:47] [Server thread/INFO]: [BetterHeads] Checking category 'food-drinks'..
[10:29:48] [Server thread/INFO]: [BetterHeads] New heads found in category 'food-drinks'. Loading new heads..
[10:29:48] [Server thread/INFO]: [BetterHeads] Added 1703 new heads..
[10:29:48] [Server thread/INFO]: [BetterHeads] Checking category 'humans'..
[10:30:05] [Server thread/INFO]: [BetterHeads] New heads found in category 'humans'. Loading new heads..
[10:30:05] [Server thread/INFO]: [BetterHeads] Added 11331 new heads..
[10:30:07] [Server thread/INFO]: [BetterHeads] Checking category 'humanoid'..
[10:30:13] [Server thread/INFO]: [BetterHeads] New heads found in category 'humanoid'. Loading new heads..
[10:30:13] [Server thread/INFO]: [BetterHeads] Added 6602 new heads..
[10:30:14] [Server thread/INFO]: [BetterHeads] Checking category 'miscellaneous'..
[10:30:15] [Server thread/INFO]: [BetterHeads] New heads found in category 'miscellaneous'. Loading new heads..
[10:30:15] [Server thread/INFO]: [BetterHeads] Added 2287 new heads..
[10:30:16] [Server thread/INFO]: [BetterHeads] Checking category 'monsters'..
[10:30:18] [Server thread/INFO]: [BetterHeads] New heads found in category 'monsters'. Loading new heads..
[10:30:18] [Server thread/INFO]: [BetterHeads] Added 3295 new heads..
[10:30:20] [Server thread/INFO]: [BetterHeads] Checking category 'plants'..
[10:30:20] [Server thread/INFO]: [BetterHeads] New heads found in category 'plants'. Loading new heads..
[10:30:20] [Server thread/INFO]: [BetterHeads] Added 1060 new heads..
[10:30:21] [Server thread/INFO]: [BetterHeads] New heads found: 48362
[10:30:21] [Server thread/INFO]: [BetterHeads] Loading 48362 heads from heads.yml.. This is a huge amount of heads.
[10:30:21] [Server thread/INFO]: [BetterHeads] This process can take a while, please be patient.
[10:30:25] [Server thread/INFO]: [BetterHeads] Updated heads.yml successfully!
[10:30:25] [Server thread/INFO]: [BetterHeads] Categories found (10): alphabet, animals, blocks, decoration, food-drinks, humans, humanoid, miscellaneous, monsters, plants
```

**To Reproduce**
Simply install the plugin on one of the latest paper builds.

**Expected behavior**
Perhaps use another file format than YAML to store all this data

**Important (please complete the following information):**
 - Java version: irrelevant for this but I'm running Java 17
 - Plugin version: 1.3-BETA
 - Server version: This server is running Paper version git-Paper-173 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: abe53a7)
You are running the latest version
Previous version: git-Paper-161 (MC: 1.19.2)

**Comment by AlonsoAliaga** [comment]
I see the error, however I can't implement a fix for now.
The only option for now is using a past build of Paper (ie. Paper 1.19.2 build 161) until this can be fixed.

I'll let you know here when there is a build of BetterHeads ready to be tested in newer builds.
(Additionally, please try with latest latest latest latest paper version)

**Comment by AlonsoAliaga** [comment]
Updating to latest build of Paper should have fixed the issue.
